import type { HTMLAttributes } from "react";

// Fixture for a variant whose name collides with an HTML attribute.
// Builds the same shape as `VariantProps<typeof badgeVariants>` without pulling in cva.
// What matters is that the variant's props are generated by a mapped type.
// A mapped type's properties have no declaration node in the host's file, so
// looking at where a single prop is declared can't tell it apart from "a prop the host declared".

type BadgeVariantConfig = {
	color: { primary: string; danger: string };
	size: { sm: string; md: string };
};

// The equivalent of cva's VariantProps. Folds variant name -> union of choices.
type VariantProps<T> = { [K in keyof T]?: keyof T[K] | null };

/** A badge with a variant that collides with an HTML attribute. */
export function CollidingBadge({
	color,
	size,
	...props
}: HTMLAttributes<HTMLSpanElement> & VariantProps<BadgeVariantConfig>) {
	return <span data-color={color} data-size={size} {...props} />;
}
