import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import {
	mkdir,
	mkdtemp,
	readdir,
	readFile,
	rm,
	writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
	DEFAULT_DATA_DIR,
	ensureDataDir,
	screensDir,
	seedDataDir,
} from "./config.ts";

// The default save location must be on the host side. Moving it back inside the package would
// wipe the user's screens on reinstall, and would also fail to write in environments where
// node_modules is read-only.
describe("DEFAULT_DATA_DIR", () => {
	it("パッケージ内ではなく cwd 配下を指す", () => {
		expect(DEFAULT_DATA_DIR).toBe(join(process.cwd(), ".yosegi"));
		expect(DEFAULT_DATA_DIR).not.toContain("node_modules");
	});
});

// Verifies seedDataDir's first-run seeding and its "deleted screens don't come back" behavior.
describe("seedDataDir", () => {
	let dir: string;

	beforeEach(async () => {
		dir = await mkdtemp(join(tmpdir(), "vc-config-"));
	});

	afterEach(async () => {
		await rm(dir, { recursive: true, force: true });
	});

	it("初回はシード画面をコピーする", async () => {
		await seedDataDir(dir);
		const files = await readdir(screensDir(dir));
		expect(files.some((f) => f.endsWith(".json"))).toBe(true);
	});

	it("全画面を削除して再実行しても復活しない", async () => {
		await seedDataDir(dir);
		// Reproduces the situation where the user deleted every screen.
		for (const file of await readdir(screensDir(dir))) {
			await rm(join(screensDir(dir), file));
		}
		// Equivalent to a second startup. The sentinel is present, so it isn't reseeded.
		await seedDataDir(dir);
		const files = await readdir(screensDir(dir));
		expect(files.filter((f) => f.endsWith(".json"))).toHaveLength(0);
	});

	it("既存ユーザーデータがある場合はシードで上書きしない", async () => {
		// The case where only user screens exist, with no sentinel yet.
		await mkdir(screensDir(dir), { recursive: true });
		await writeFile(join(screensDir(dir), "mine.json"), "{}");
		await seedDataDir(dir);
		const files = await readdir(screensDir(dir));
		expect(files).toContain("mine.json");
		// The seed screens are not applied (the sentinel is set, so future runs skip it).
		expect(files.filter((f) => f.endsWith(".json"))).toHaveLength(1);
	});
});

// The data dir is build output, and a host should not have to discover that from a dirty
// `git status` after its first command.
describe("ensureDataDir", () => {
	let dir: string;

	beforeEach(async () => {
		dir = join(await mkdtemp(join(tmpdir(), "vc-ignore-")), "data");
	});

	afterEach(async () => {
		await rm(dir, { recursive: true, force: true });
	});

	it("data-dir を作り .gitignore を書き出す", async () => {
		await ensureDataDir(dir);
		const written = await readFile(join(dir, ".gitignore"), "utf8");
		expect(written).toContain("*");
		expect(written).toContain("Generated by Yosegi");
	});

	// Committing the registry is a decision the host makes by editing this file, so a later
	// command must never undo it. Deleting it is not the opt-out — the next command that
	// creates the directory writes it again, which is why the file says so itself.
	it("既存の .gitignore は上書きしない", async () => {
		await mkdir(dir, { recursive: true });
		await writeFile(join(dir, ".gitignore"), "!registry.json\n");
		await ensureDataDir(dir);
		expect(await readFile(join(dir, ".gitignore"), "utf8")).toBe(
			"!registry.json\n",
		);
	});

	it("seedDataDir 経由でも書き出される", async () => {
		await seedDataDir(dir);
		expect(await readFile(join(dir, ".gitignore"), "utf8")).toContain("*");
	});

	// The documented opt-out, pinned end to end: a negation added to the file survives every
	// later command, where a deletion would not.
	it("否定パターンを足した .gitignore は以降のコマンドでも残る", async () => {
		await ensureDataDir(dir);
		const path = join(dir, ".gitignore");
		const opted = `${await readFile(path, "utf8")}!registry.json\n`;
		await writeFile(path, opted);
		await seedDataDir(dir);
		expect(await readFile(path, "utf8")).toBe(opted);
	});
});
